# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14jc0nyBSb_XvUmsPwJO3NpbB9XqIXATd
"""

import requests
import re
from bs4 import BeautifulSoup
import pandas as pd
from tqdm import tqdm
from datetime import datetime
import yfinance as yf

# 行数・列数ともに制限解除して全て表示
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)  # 長い文字列も切らずに表示

# 1. JPXからIPO一覧を取得
def get_jpx_ipo_list_multi_year(years=3):
    # https://www.jpx.co.jp/listing/stocks/new/00-archives-01.html
    base_url = "https://www.jpx.co.jp/listing/stocks/new/"
    suffix_list = ["index.html", "00-archives-01.html", "00-archives-02.html", "00-archives-03.html", "00-archives-04.html"]

    all_records = []

    for i in range(years):
        url = base_url + suffix_list[i]
        print(f"取得中: {url}")
        try:
            r = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
            r.encoding = r.apparent_encoding
            soup = BeautifulSoup(r.text, "lxml")

            table = soup.find("table")
            rows = table.find_all("tr")[2:]
            i = 0
            while i < len(rows) - 1:
                tr1 = rows[i]
                tr2 = rows[i + 1]
                tds1 = tr1.find_all("td")
                tds2 = tr2.find_all("td")
                try:
                    上場日 = tds1[0].get_text(strip=True).split("（")[0]
                    会社名 = tds1[1].find("a").get_text(strip=True)
                    証券コード = tds1[2].get_text(strip=True)
                    市場 = tds2[0].get_text(strip=True)
                    公募価格 = tds2[3].get_text(strip=True) if len(tds2) > 3 else ""
                    if "～" in 公募価格:
                        公募価格 = 公募価格.split("～")[-1]
                    公募価格 = int(公募価格.replace(",", "")) if 公募価格.replace(",", "").isdigit() else None
                    all_records.append({
                        "上場日": 上場日,
                        "市場": 市場,
                        "証券コード": 証券コード,
                        "企業名": 会社名,
                        "公募価格": 公募価格
                    })
                except:
                    pass
                i += 2
        except Exception as e:
            print(f"取得失敗: {url} - {e}")

    return pd.DataFrame(all_records)

# 2. yfinanceで現在株価取得
def get_current_prices(df):
    df['現在株価'] = None
    for i in tqdm(df.index, desc="現在株価取得中"):
        code = df.at[i, '証券コード'].zfill(4) + ".T"
        try:
            ticker = yf.Ticker(code)
            data = ticker.history(period="1d")
            if not data.empty:
                df.at[i, '現在株価'] = round(data['Close'].iloc[-1])
        except:
            pass
    return df

# 3. IR BANKから時価総額取得
import requests
from bs4 import BeautifulSoup
import re

def get_market_cap(code):
    try:
        url = f"https://irbank.net/{code}/cap"
        headers = {"User-Agent": "Mozilla/5.0"}
        r = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(r.content, "lxml")

        # 時価総額が入っているtdを探索
        td_list = soup.select("table#tbc tbody tr td")
        for td in td_list:
            text = td.get_text(strip=True)
            match = re.match(r"(\d+)(億)(\d+)?(万)?", text)
            if match:
                億 = int(match.group(1))
                万 = int(match.group(3)) if match.group(3) else 0
                cap = 億 + 万 / 10000  # 74億1000万 → 74.1
                return cap
        return None
    except Exception as e:
        print(f"[時価総額取得失敗] {code}: {e}")
        return None

# 4. オーナー創業社長かを判定
def is_owner_ceo(code):
    url = f"https://irbank.net/{code}/officer"
    headers = {"User-Agent": "Mozilla/5.0"}

    try:
        r = requests.get(url, headers=headers, timeout=10)
        soup = BeautifulSoup(r.content, 'lxml')
        trs = soup.find_all('tr')

        for tr in trs:
            tds = tr.find_all('td')
            if len(tds) >= 2:
                役職 = tds[1].text.strip()

                # 持株比率を抽出（パターン: 例 '45.303%'）
                match = re.search(r'\(([\d.]+)%\)', 役職)
                ratio = float(match.group(1)) if match else 0.0
                # 表示出力（備考を「前期:」に変更）
                # print(f"[{code}] 役職: {役職} | 比率: {ratio}%")

                if '取締役' in 役職 and ratio >= 40:
                    return True
        return False
    except Exception as e:
        print(f"[{code}] エラー: {e}")
        return False

# 5. 一括処理
df = get_jpx_ipo_list_multi_year(years=5)
df = get_current_prices(df)
df['時価総額'] = df['証券コード'].apply(get_market_cap)
df['オーナー創業社長'] = df['証券コード'].apply(is_owner_ceo)

# 6. フィルタ適用
df['上場年'] = df['上場日'].str[:4].astype(int)
year_limit = datetime.now().year - 10

# None や不正な文字列を NaN にする
df['現在株価'].apply(lambda x: isinstance(x, (int, float)))
df['公募価格'].apply(lambda x: isinstance(x, (int, float)))
df['時価総額'] = pd.to_numeric(df['時価総額'], errors='coerce').fillna(0)

# 条件フィルターの適用
# df_filtered = df[
#     df['上場年'] >= year_limit &
#     df['公募価格'].notnull() &
#     df['現在株価'].notnull() &
#     (df['現在株価'] < df['公募価格']) &
#     (df['時価総額'] >= 30) &
#     (df['時価総額'] <= 700) &
#     (df['オーナー創業社長'] == True)
# ]

# 元の DataFrame をコピー
df_filtered = df.copy()

# 上場年フィルタ
# df_filtered = df_filtered[df_filtered['上場年'] >= year_limit]
# print(f"[上場年 >= {year_limit}] -> {len(df_filtered)} 件")

# 公募価格あり
df_filtered = df_filtered[df_filtered['公募価格'].notnull()]
print(f"[公募価格 notnull] -> {len(df_filtered)} 件")

# 現在株価あり
df_filtered = df_filtered[df_filtered['現在株価'].notnull()]
print(f"[現在株価 notnull] -> {len(df_filtered)} 件")

# 現在株価 < 公募価格
df_filtered = df_filtered[df_filtered['現在株価'] < df_filtered['公募価格']]
print(f"[現在株価 < 公募価格] -> {len(df_filtered)} 件")

# 時価総額が数値であることを確認（intに変換）
df_filtered['時価総額'] = pd.to_numeric(df_filtered['時価総額'], errors='coerce')
df_filtered = df_filtered[df_filtered['時価総額'].notnull()]
print(f"[時価総額 notnull] -> {len(df_filtered)} 件")

# 時価総額が 30 以上 700 以下
df_filtered = df_filtered[(df_filtered['時価総額'] >= 30) & (df_filtered['時価総額'] <= 700)]
print(f"[30 <= 時価総額 <= 700] -> {len(df_filtered)} 件")

# オーナー創業社長が True
df_filtered = df_filtered[df_filtered['オーナー創業社長'] == True]
print(f"[オーナー創業社長 == True] -> {len(df_filtered)} 件")

# 7. 出力
print("\n=== 条件をすべて満たすIPO銘柄 ===")
print(df_filtered[['証券コード', '企業名', '上場日', '現在株価', '公募価格', '時価総額']])